---
app:
 # CORS
  cors:
    enabled: true
    allowedOrigin: '*'
    allowedMethods: GET,POST,PUT,DELETE
    allowedHeaders:
      - Authorization
      - X-Requested-With
      - Content-Type
    maxAge: 3600

  # Swagger
  swagger:
    enabled: true

  persistence:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
#      url: jdbc:mysql://localhost:3306/asio_jobs?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      url: jdbc:mysql://localhost:3307/asio_jobs?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    poolProperties:
      maxPool: 100
      minIdle: 15
  kafka:
    input-topic-name: input-data
    create-topics: true
  data:
    path: C:\desarrollo\murcia\dataset
  services:    
    cvn:
      mockup:
        enabled: false    
      endpoint: http://curriculumpruebas.um.es/curriculum/rest/v1/auth
      endpoint-cvn: /cvn
      endpoint-changes: /changes
    input-processor:
      mockup:
        enabled: false    
      endpoint: http://localhost:9322
      endpoint-import-search: ${app.services.input-processor.endpoint}/import-result/search      
# SGI  
    oai:      
      endpoint: http://herc-as-front-desa.atica.um.es/oai-pmh-xml/OAI_PMH
      endpoint-list: ?verb=ListSets
      endpoint-xml: ?verb=GetRecord&metadataPrefix=XML_ASIO&identifier=
      endpoint-ids: ?verb=ListIdentifiers&metadataPrefix=XML_ASIO&set=

# CERIF  
    cerif:      
      endpoint: https://cris.uns.ac.rs/OAIHandlerOpenAIRECRIS
      endpoint-list: ${app.services.cerif.endpoint}?verb=ListSets
      endpoint-xml: ${app.services.cerif.endpoint}?verb=GetRecord&metadataPrefix=oai_cerif_openaire&identifier=
      endpoint-ids: ${app.services.cerif.endpoint}?verb=ListIdentifiers&metadataPrefix=oai_cerif_openaire&set=
      
      
# Spring configuration
spring:
  batch:    
    initialize-schema: never
    # Dont launch jobs automatically
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers:
      - localhost:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

## Actuator
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      base-path: /management
  server:
    port: 9322
  health:
    mail:
      enabled: false
    ldap:
      enabled: false
    redis:
      enabled: false
## In case of configure web endpoints, remove it or change port number
server:
  port: ${management.server.port}    
