---
app:
  persistence:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
#      url: jdbc:mysql://localhost:3306/asio_jobs?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      url: jdbc:mysql://localhost:3307/asio_jobs?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  kafka:
    input-topic-name: input-data
    create-topics: false
  data:
    path:
  services:    
    cvn:
      mockup:
        enabled: true    
      endpoint: http://curriculumpruebas.um.es/curriculum/rest/v1/auth
      endpoint-cvn: ${app.services.cvn.endpoint}/cvn
      endpoint-changes: ${app.services.cvn.endpoint}/changes
    input-processor:
      mockup:
        enabled: true    
      endpoint: http://localhost:9322
      endpoint-import-search: ${app.services.input-processor.endpoint}/import-result/search?

# Spring configuration
spring:
  batch:
    initialize-schema: never
    # Dont launch jobs automatically
    # job:
      # enabled: false
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers:
      - localhost:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
